const ADMIN_URL='https://oansbivjkczjbtxaknks.supabase.co';
const ADMIN_KEY='sb_publishable_9tDZPZ9KmCjHZqVXBmO-1g_8Aqpu8qE';
const adminDb=window.supabase.createClient(ADMIN_URL,ADMIN_KEY);
const admin$=s=>document.querySelector(s);
const adminMoney=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const adminEsc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
let adminUser=null,adminIsAdmin=false;
function notifyAdmin(t){if(typeof toast==='function')toast(t)}
async function checkAdmin(){const {data}=await adminDb.auth.getSession();adminUser=data.session?.user||null;if(!adminUser){adminIsAdmin=false;showAdminGate();return false}const {data:profile}=await adminDb.from('profiles').select('role').eq('id',adminUser.id).maybeSingle();adminIsAdmin=profile?.role==='admin';if(adminIsAdmin)showAdminContent();else showAdminGate();return adminIsAdmin}
function showAdminGate(){admin$('#adminNavBtn')?.classList.add('hidden');admin$('#adminContent')?.classList.add('hidden');admin$('#adminGate')?.classList.remove('hidden')}
function showAdminContent(){admin$('#adminNavBtn')?.classList.remove('hidden');admin$('#adminGate')?.classList.add('hidden');admin$('#adminContent')?.classList.remove('hidden')}
function periodStart(){const v=admin$('#adminPeriod').value;if(v==='all')return null;const d=new Date();d.setDate(d.getDate()-Number(v)+1);d.setHours(0,0,0,0);return d.toISOString()}
async function loadAdminStats(){if(!adminIsAdmin)return;const start=periodStart();const [{data:stats,error:statsErr},{data:merchants,error:merchantErr},{data:orders,error:orderErr},{data:payouts,error:payoutErr}]=await Promise.all([adminDb.rpc('admin_dashboard_stats',{p_start:start}),adminDb.rpc('admin_merchants',{p_start:start}),adminDb.rpc('admin_orders',{p_start:start}),adminDb.rpc('admin_payouts',{p_start:start})]);if(statsErr){notifyAdmin(statsErr.message);return}if(merchantErr||orderErr||payoutErr){notifyAdmin((merchantErr||orderErr||payoutErr).message);return}const s=stats||{};admin$('#adminStats').innerHTML=`<div class="admin-stat-card"><strong>${s.users||0}</strong><span>Registrierte Nutzer</span></div><div class="admin-stat-card"><strong>${s.merchants||0}</strong><span>Händler</span></div><div class="admin-stat-card"><strong>${s.orders||0}</strong><span>Bestellungen</span></div><div class="admin-stat-card"><strong>${adminMoney(s.revenue)}</strong><span>Umsatz</span></div><div class="admin-stat-card"><strong>${adminMoney(s.commission)}</strong><span>Provision</span></div><div class="admin-stat-card"><strong>${adminMoney(s.pending_payouts)}</strong><span>Offene Auszahlungen</span></div>`;admin$('#merchantTotal').textContent=`${(merchants||[]).length} Händler`;admin$('#adminOrderTotal').textContent=`${(orders||[]).length} Bestellungen`;
admin$('#merchantTable').innerHTML=(merchants||[]).map(m=>`<div class="admin-table-row"><div><strong>${adminEsc(m.shop_name)}</strong><span>${adminEsc(m.owner_name||'Händler')} · ${adminEsc(m.status)}</span></div><div class="admin-merchant-actions"><strong>${Number(m.commission_rate).toFixed(1)}%</strong><small>Provision</small><select data-merchant-status="${adminEsc(m.id)}"><option value="pending" ${m.status==='pending'?'selected':''}>Ausstehend</option><option value="approved" ${m.status==='approved'?'selected':''}>Freigegeben</option><option value="rejected" ${m.status==='rejected'?'selected':''}>Abgelehnt</option><option value="suspended" ${m.status==='suspended'?'selected':''}>Gesperrt</option></select></div></div>`).join('')||'<p class="muted">Noch keine Händler.</p>';
admin$('#merchantTable').querySelectorAll('[data-merchant-status]').forEach(el=>el.addEventListener('change',()=>updateMerchantStatus(el.dataset.merchantStatus,el.value)));
admin$('#adminOrderTable').innerHTML=(orders||[]).slice(0,20).map(o=>`<div class="admin-table-row"><div><strong>#${o.id}</strong><span>${adminEsc(o.status)} · ${new Date(o.created_at).toLocaleDateString('de-DE')}</span></div><div><strong>${adminMoney(o.total)}</strong><small>Provision ${adminMoney(o.commission_amount)}</small></div></div>`).join('')||'<p class="muted">Noch keine Bestellungen.</p>';
admin$('#payoutTable').innerHTML=(payouts||[]).slice(0,20).map(p=>`<div class="admin-table-row"><div><strong>Händler #${String(p.merchant_id).slice(0,8)}</strong><span>${new Date(p.created_at).toLocaleDateString('de-DE')}</span></div><div><strong>${adminMoney(p.amount)}</strong><small>${adminEsc(p.status)}</small></div></div>`).join('')||'<p class="muted">Noch keine Auszahlungen.</p>';
admin$('#adminSystem').innerHTML=`<div><span>Angemeldet</span><strong>${adminEsc(adminUser.email||'')}</strong></div><div><span>Admin</span><strong>Aktiv</strong></div><div><span>Zeitraum</span><strong>${admin$('#adminPeriod').selectedOptions[0].textContent}</strong></div><div><span>Bereitgestellte Provisionen</span><strong>${adminMoney(s.commission)}</strong></div>`}
async function updateMerchantStatus(id,status){if(!adminIsAdmin)return;const {error}=await adminDb.rpc('admin_set_merchant_status',{p_merchant_id:id,p_status:status});if(error){notifyAdmin(error.message);return}notifyAdmin(status==='approved'?'Händler freigegeben':status==='rejected'?'Händler abgelehnt':status==='suspended'?'Händler gesperrt':'Händler auf ausstehend gesetzt');await loadAdminStats()}
async function saveCommission(){if(!adminIsAdmin)return;const rate=Number(admin$('#defaultCommission').value);if(!Number.isFinite(rate)||rate<0||rate>100)return notifyAdmin('Provision muss zwischen 0 und 100 % liegen');const {error}=await adminDb.rpc('admin_set_default_commission',{p_rate:rate});if(error)notifyAdmin(error.message);else{notifyAdmin('Provisionssatz gespeichert');await loadAdminStats()}}
function switchToAdmin(){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));admin$('#adminView')?.classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));admin$('#adminNavBtn')?.classList.add('active');checkAdmin().then(ok=>{if(ok)loadAdminStats()})}
admin$('#adminNavBtn')?.addEventListener('click',switchToAdmin);admin$('#refreshAdmin')?.addEventListener('click',loadAdminStats);admin$('#adminPeriod')?.addEventListener('change',loadAdminStats);admin$('#saveCommission')?.addEventListener('click',saveCommission);adminDb.auth.onAuthStateChange(()=>setTimeout(checkAdmin,0));checkAdmin();