const ADMIN_URL='https://oansbivkczjbtxaknks.supabase.co';
const ADMIN_KEY='sb_publishable_9tDZPZ9KmCjHZqVXBmO-1g_8Aqpu8qE';
const adminDb=window.supabase.createClient(ADMIN_URL,ADMIN_KEY);
const admin$=s=>document.querySelector(s);
const adminMoney=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const adminEsc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let adminUser=null,adminIsAdmin=false;
function notifyAdmin(t){if(typeof toast==='function')toast(t)}
async function checkAdmin(){const {data}=await adminDb.auth.getSession();adminUser=data.session?.user||null;if(!adminUser){adminIsAdmin=false;showAdminGate();return false}const {data:profile}=await adminDb.from('profiles').select('role').eq('id',adminUser.id).maybeSingle();adminIsAdmin=profile?.role==='admin';if(adminIsAdmin)showAdminContent();else showAdminGate();return adminIsAdmin}
function showAdminGate(){admin$('#adminNavBtn').classList.add('hidden');admin$('#adminContent').classList.add('hidden');admin$('#adminGate').classList.remove('hidden')}
function showAdminContent(){admin$('#adminNavBtn').classList.remove('hidden');admin$('#adminGate').classList.add('hidden');admin$('#adminContent').classList.remove('hidden')}
async function loadCommission(){const {data,error}=await adminDb.from('platform_settings').select('default_commission_rate').eq('id',true).single();if(!error&&data)admin$('#defaultCommission').value=data.default_commission_rate}
function periodStart(){const v=admin$('#adminPeriod').value;if(v==='all')return null;const d=new Date();d.setDate(d.getDate()-Number(v)+1);d.setHours(0,0,0,0);return d.toISOString()}
async function loadAdminStats(){if(!adminIsAdmin)return;const start=periodStart();let uq=adminDb.from('profiles').select('id,role,created_at');let mq=adminDb.from('merchants').select('id,shop_name,status,commission_rate,owner_id,created_at');let oq=adminDb.from('orders').select('id,status,total,commission_amount,customer_id,created_at').order('created_at',{ascending:false});let pq=adminDb.from('platform_payouts').select('id,merchant_id,amount,status,created_at,paid_at').order('created_at',{ascending:false});if(start){uq=uq.gte('created_at',start);mq=mq.gte('created_at',start);oq=oq.gte('created_at',start);pq=pq.gte('created_at',start)}const [{data:users},{data:merchants},{data:orders},{data:payouts}]=await Promise.all([uq,mq,oq,pq]);const us=users||[],ms=merchants||[],os=orders||[],ps=payouts||[];const revenue=os.reduce((s,o)=>s+Number(o.total||0),0),commission=os.reduce((s,o)=>s+Number(o.commission_amount||0),0),pending=ps.filter(p=>p.status==='pending').reduce((s,p)=>s+Number(p.amount||0),0),paid=ps.filter(p=>p.status==='paid').reduce((s,p)=>s+Number(p.amount||0),0);admin$('#adminStats').innerHTML=`<div class="admin-stat-card"><strong>${us.length}</strong><span>Registrierte Nutzer</span></div><div class="admin-stat-card"><strong>${ms.length}</strong><span>Händler</span></div><div class="admin-stat-card"><strong>${os.length}</strong><span>Bestellungen</span></div><div class="admin-stat-card"><strong>${adminMoney(revenue)}</strong><span>Umsatz</span></div><div class="admin-stat-card"><strong>${adminMoney(commission)}</strong><span>Provision</span></div><div class="admin-stat-card"><strong>${adminMoney(pending)}</strong><span>Offene Auszahlungen</span></div>`;admin$('#merchantTotal').textContent=`${ms.length} Händler`;admin$('#adminOrderTotal').textContent=`${os.length} Bestellungen`;
const ownerIds=[...new Set(ms.map(m=>m.owner_id))];let names={};if(ownerIds.length){const {data:owners}=await adminDb.from('profiles').select('id,display_name').in('id',ownerIds);(owners||[]).forEach(x=>names[x.id]=x.display_name||x.id.slice(0,8))}
admin$('#merchantTable').innerHTML=ms.map(m=>`<div class="admin-table-row"><div><strong>${adminEsc(m.shop_name)}</strong><span>${adminEsc(names[m.owner_id]||'Händler')} · ${adminEsc(m.status)}</span></div><div><strong>${Number(m.commission_rate).toFixed(1)}%</strong><small>Provision</small></div></div>`).join('')||'<p class="muted">Noch keine Händler.</p>';
admin$('#adminOrderTable').innerHTML=os.slice(0,20).map(o=>`<div class="admin-table-row"><div><strong>#${o.id}</strong><span>${adminEsc(o.status)} · ${new Date(o.created_at).toLocaleDateString('de-DE')}</span></div><div><strong>${adminMoney(o.total)}</strong><small>Provision ${adminMoney(o.commission_amount)}</small></div></div>`).join('')||'<p class="muted">Noch keine Bestellungen.</p>';
admin$('#payoutTable').innerHTML=ps.slice(0,20).map(p=>`<div class="admin-table-row"><div><strong>Händler #${p.merchant_id.slice(0,8)}</strong><span>${new Date(p.created_at).toLocaleDateString('de-DE')}</span></div><div><strong>${adminMoney(p.amount)}</strong><small>${adminEsc(p.status)}</small></div></div>`).join('')||'<p class="muted">Noch keine Auszahlungen.</p>';
admin$('#adminSystem').innerHTML=`<div><span>Angemeldet</span><strong>${adminEsc(adminUser.email||'')}</strong></div><div><span>Admin</span><strong>Aktiv</strong></div><div><span>Zeitraum</span><strong>${admin$('#adminPeriod').selectedOptions[0].textContent}</strong></div>`}
async function saveCommission(){if(!adminIsAdmin)return;const rate=Number(admin$('#defaultCommission').value);if(!Number.isFinite(rate)||rate<0||rate>100)return notifyAdmin('Provision muss zwischen 0 und 100 % liegen');const {error}=await adminDb.from('platform_settings').update({default_commission_rate:rate,updated_at:new Date().toISOString()}).eq('id',true);if(error)notifyAdmin(error.message);else{notifyAdmin('Provisionssatz gespeichert');await loadAdminStats()}}
function switchToAdmin(){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));admin$('#adminView').classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));admin$('#adminNavBtn').classList.add('active');checkAdmin().then(()=>{loadCommission();loadAdminStats()})}
admin$('#adminNavBtn').addEventListener('click',switchToAdmin);admin$('#refreshAdmin').addEventListener('click',()=>loadAdminStats());admin$('#adminPeriod').addEventListener('change',loadAdminStats);admin$('#saveCommission').addEventListener('click',saveCommission);
adminDb.auth.onAuthStateChange(()=>setTimeout(checkAdmin,0));checkAdmin();
