const seedProducts=[
 {id:1,name:'Motorsport Hoodie Unisex',category:'Hoodies',price:59.90,stock:24,description:'Racing Streetwear Kapuzenpullover für Motorsport-Fans.',image:''},
 {id:2,name:'KartracingJamie24 Fan-Shirt',category:'T-Shirts',price:29.90,stock:42,description:'Motorsport Fan-Shirt im Racing Style.',image:''},
 {id:3,name:'Heavyweight Unisex Boxy T-Shirt',category:'T-Shirts',price:34.90,stock:18,description:'Schweres Boxy T-Shirt mit modernem Schnitt.',image:''},
 {id:4,name:'Stanley/Stella Bio-Poloshirt PREPSTER',category:'Polos',price:44.90,stock:15,description:'Hochwertiges Bio-Poloshirt für Alltag und Rennstrecke.',image:''},
 {id:5,name:'Snapback Cap Racing',category:'Accessories',price:24.90,stock:31,description:'Racing Cap mit klassischem Snapback-Verschluss.',image:''},
 {id:6,name:'Roll Top Backpack',category:'Accessories',price:49.90,stock:12,description:'Praktischer Rolltop-Rucksack im Motorsport-Look.',image:''}
];
let products=JSON.parse(localStorage.getItem('rebel_products')||'null')||seedProducts;
let cart=JSON.parse(localStorage.getItem('rebel_cart')||'[]');
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
function save(){localStorage.setItem('rebel_products',JSON.stringify(products));localStorage.setItem('rebel_cart',JSON.stringify(cart));}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function categories(){const select=$('#categoryFilter');const cats=[...new Set(products.map(p=>p.category))].sort();select.innerHTML='<option value="all">Alle Kategorien</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('')}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderShop(){categories();let q=$('#search').value.toLowerCase();let cat=$('#categoryFilter').value;let list=products.filter(p=>(p.name+' '+p.description).toLowerCase().includes(q)&&(cat==='all'||p.category===cat));const sort=$('#sort').value;if(sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(sort==='priceDesc')list.sort((a,b)=>b.price-a.price);$('#productGrid').innerHTML=list.map(p=>`<article class="product">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'<div class="placeholder">RK</div>'}<div class="product-body"><div class="muted">${esc(p.category)}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description)}</p><div class="price">${money(p.price)}</div><button class="add" onclick="addToCart(${p.id})">In den Warenkorb</button></div></article>`).join('')||'<p>Keine Produkte gefunden.</p>'}
function renderDashboard(){const revenue=products.reduce((s,p)=>s+p.price*Math.max(0,10-p.stock/10),0);$('#stats').innerHTML=`<div class="stat"><strong>${products.length}</strong><span>Produkte</span></div><div class="stat"><strong>${products.reduce((s,p)=>s+p.stock,0)}</strong><span>Artikel auf Lager</span></div><div class="stat"><strong>€${revenue.toFixed(0)}</strong><span>Beispielumsatz</span></div><div class="stat"><strong>3</strong><span>Offene Bestellungen</span></div>`;$('#productTotal').textContent=`${products.length} Produkte`;$('#adminProducts').innerHTML=products.map(p=>`<div class="admin-row"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.category)} · ${money(p.price)} · Bestand ${p.stock}</div></div><div class="admin-actions"><button onclick="editProduct(${p.id})">Bearbeiten</button><button onclick="deleteProduct(${p.id})">Löschen</button></div></div>`).join('');const orders=[['#RK-1004','Motorsport Hoodie Unisex','59,90 €','In Bearbeitung'],['#RK-1003','Fan-Shirt + Cap','54,80 €','Bezahlt'],['#RK-1002','Boxy T-Shirt','34,90 €','Versendet']];$('#orders').innerHTML=orders.map(o=>`<div class="order-row"><div><strong>${o[0]}</strong><div class="muted">${o[1]} · ${o[2]}</div></div><span class="muted">${o[3]}</span></div>`).join('')}
function switchView(view){$('#shopView').classList.toggle('hidden',view!=='shop');$('#dashboardView').classList.toggle('hidden',view!=='dashboard');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='dashboard')renderDashboard();if(view==='shop')renderShop()}
function openProduct(p){$('#productModal').classList.remove('hidden');$('#modalTitle').textContent=p?'Produkt bearbeiten':'Produkt hinzufügen';$('#productId').value=p?.id||'';$('#name').value=p?.name||'';$('#category').value=p?.category||'';$('#price').value=p?.price||'';$('#stock').value=p?.stock??'';$('#image').value=p?.image||'';$('#description').value=p?.description||''}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save();updateCartCount();toast('Produkt hinzugefügt')}
function updateCartCount(){$('#cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0)}
function renderCart(){$('#cartItems').innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`<div class="admin-row"><div><strong>${esc(p.name)}</strong><div class="muted">${i.qty} × ${money(p.price)}</div></div><div class="admin-actions"><button onclick="changeQty(${p.id},-1)">−</button><button onclick="changeQty(${p.id},1)">+</button></div></div>`:''}).join(''):'<p class="muted">Dein Warenkorb ist leer.</p>';$('#cartTotal').textContent=money(cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0));}
function changeQty(id,d){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);save();updateCartCount();renderCart()}
window.addToCart=addToCart;window.editProduct=id=>openProduct(products.find(p=>p.id===id));window.deleteProduct=id=>{if(confirm('Produkt wirklich löschen?')){products=products.filter(p=>p.id!==id);save();renderDashboard();renderShop();toast('Produkt gelöscht')}};window.changeQty=changeQty;
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
['search','categoryFilter','sort'].forEach(id=>$('#'+id).addEventListener('input',renderShop));
$('#addProductBtn').addEventListener('click',()=>openProduct());
$('#productForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#productId').value;const data={id:id?Number(id):Date.now(),name:$('#name').value.trim(),category:$('#category').value.trim(),price:Number($('#price').value),stock:Number($('#stock').value),image:$('#image').value.trim(),description:$('#description').value.trim()};if(id)products=products.map(p=>p.id===Number(id)?data:p);else products.unshift(data);save();$('#productModal').classList.add('hidden');renderDashboard();renderShop();toast('Produkt gespeichert')});
$('#cartBtn').addEventListener('click',()=>{$('#cartModal').classList.remove('hidden');renderCart()});
$('#checkoutBtn').addEventListener('click',()=>toast('Checkout wird als nächster Schritt angebunden'));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.add('hidden')));
updateCartCount();renderShop();
