const SUPABASE_URL='https://oansbivjkczjbtxaknks.supabase.co';
const SUPABASE_KEY='sb_publishable_9tDZPZ9KmCjHZqVXBmO-1g_8Aqpu8qE';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let products=[]; let cart=JSON.parse(localStorage.getItem('rebel_cart')||'[]'); let currentUser=null; let merchant=null; let authMode='login';
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
async function loadProducts(){const {data,error}=await db.from('products').select('id,name,slug,description,price,stock,image_url,created_at,category_id,categories(name)').eq('active',true).order('created_at',{ascending:false});if(error){console.error(error);toast('Produkte konnten nicht geladen werden');return}products=(data||[]).map(p=>({...p,category:p.categories?.name||'Produkte',image:p.image_url||''}));renderShop()}
function categories(){const select=$('#categoryFilter');const cats=[...new Set(products.map(p=>p.category))].sort();select.innerHTML='<option value="all">Alle Kategorien</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}
function renderShop(){categories();let q=$('#search').value.toLowerCase(),cat=$('#categoryFilter').value,list=products.filter(p=>(p.name+' '+(p.description||'')).toLowerCase().includes(q)&&(cat==='all'||p.category===cat));const sort=$('#sort').value;if(sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(sort==='priceDesc')list.sort((a,b)=>b.price-a.price);$('#productGrid').innerHTML=list.map(p=>`<article class="product">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'<div class="placeholder">RK</div>'}<div class="product-body"><div class="muted">${esc(p.category)}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description||'')}</p><div class="price">${money(p.price)}</div><button class="add" ${p.stock<=0?'disabled':''} onclick="addToCart(${p.id})">${p.stock>0?'In den Warenkorb':'Ausverkauft'}</button></div></article>`).join('')||'<p>Keine Produkte gefunden.</p>'}
async function refreshAuth(){const {data}=await db.auth.getSession();currentUser=data.session?.user||null;if(currentUser){$('#authStatus').textContent=currentUser.email;$('#authBtn').textContent='Abmelden';await loadMerchant()}else{$('#authStatus').textContent='';$('#authBtn').textContent='Anmelden';merchant=null}}
async function loadMerchant(){if(!currentUser)return;const {data,error}=await db.from('merchants').select('*').eq('owner_id',currentUser.id).maybeSingle();if(error)console.error(error);merchant=data||null}
function setAuthMode(mode){authMode=mode;$('#authTitle').textContent=mode==='login'?'Anmelden':'Konto erstellen';$('#authSubmit').textContent=mode==='login'?'Anmelden':'Konto erstellen';$('#authNameWrap').classList.toggle('hidden',mode==='login');$('#authSwitchText').innerHTML=mode==='login'?'Noch kein Konto? <button type="button" id="authSwitch" class="link-btn">Konto erstellen</button>':'Schon ein Konto? <button type="button" id="authSwitch" class="link-btn">Anmelden</button>';$('#authSwitch').onclick=()=>setAuthMode(mode==='login'?'signup':'login')}
async function submitAuth(e){e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();if(authMode==='login'){const {error}=await db.auth.signInWithPassword({email,password});if(error){toast(error.message);return}toast('Erfolgreich angemeldet')}else{const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0]}}});if(error){toast(error.message);return}toast(data.session?'Konto erstellt':'Bitte E-Mail bestätigen')}$('#authModal').classList.add('hidden');await refreshAuth()}
async function createMerchant(){if(!currentUser)return false;if(merchant)return true;const shopName=prompt('Wie soll dein Händler-Shop heißen?','Mein Rebelkultur Shop');if(!shopName)return false;let slug=shopName.toLowerCase().trim().replace(/[^a-z0-9äöüß]+/g,'-').replace(/^-|-$/g,'').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss')||'shop';slug=`${slug}-${currentUser.id.slice(0,8)}`;const {data,error}=await db.from('merchants').insert({owner_id:currentUser.id,shop_name:shopName,slug,status:'pending'}).select().single();if(error){toast(error.message);return false}merchant=data;toast('Händler-Shop angelegt');return true}
async function renderDashboard(){if(!currentUser){$('#stats').innerHTML='<div class="stat"><strong>🔒</strong><span>Anmeldung erforderlich</span></div>';$('#adminProducts').innerHTML='<p class="muted">Bitte anmelden, um den Händlerbereich zu öffnen.</p>';$('#orders').innerHTML='<p class="muted">Noch nicht angemeldet.</p>';return}if(!merchant){await createMerchant();if(!merchant)return}const {data:list,error}=await db.from('products').select('id,name,description,price,stock,image_url,created_at,categories(name)').eq('merchant_id',merchant.id).order('created_at',{ascending:false});if(error){toast(error.message);return}const mine=(list||[]).map(p=>({...p,category:p.categories?.name||'Produkte'}));$('#stats').innerHTML=`<div class="stat"><strong>${mine.length}</strong><span>Produkte</span></div><div class="stat"><strong>${mine.reduce((s,p)=>s+p.stock,0)}</strong><span>Artikel auf Lager</span></div><div class="stat"><strong>${money(mine.reduce((s,p)=>s+Number(p.price)*p.stock,0))}</strong><span>Lagerwert</span></div><div class="stat"><strong>${esc(merchant.status)}</strong><span>Shop-Status</span></div>`;$('#productTotal').textContent=`${mine.length} Produkte`;$('#adminProducts').innerHTML=mine.map(p=>`<div class="admin-row"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.category)} · ${money(p.price)} · Bestand ${p.stock}</div></div><div class="admin-actions"><button onclick="editProduct(${p.id})">Bearbeiten</button><button onclick="deleteProduct(${p.id})">Löschen</button></div></div>`).join('')||'<p class="muted">Noch keine Produkte. Lege dein erstes Produkt an.</p>';$('#orders').innerHTML='<p class="muted">Bestellverwaltung wird als nächster Plattform-Schritt mit Händler-Zuordnung verbunden.</p>'}
function switchView(view){$('#shopView').classList.toggle('hidden',view!=='shop');$('#dashboardView').classList.toggle('hidden',view!=='dashboard');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='dashboard')renderDashboard();else renderShop()}
function openProduct(p){if(!merchant){toast('Bitte zuerst einen Händler-Shop anlegen');return}$('#productModal').classList.remove('hidden');$('#modalTitle').textContent=p?'Produkt bearbeiten':'Produkt hinzufügen';$('#productId').value=p?.id||'';$('#name').value=p?.name||'';$('#category').value=p?.category||'';$('#price').value=p?.price??'';$('#stock').value=p?.stock??'';$('#image').value=p?.image_url||p?.image||'';$('#description').value=p?.description||''}
async function addToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock<1)return;const item=cart.find(x=>x.id===id);if(item){if(item.qty>=p.stock)return toast('Nicht mehr auf Lager');item.qty++}else cart.push({id,qty:1});saveCart();updateCartCount();toast('Produkt hinzugefügt')}
function saveCart(){localStorage.setItem('rebel_cart',JSON.stringify(cart))}function updateCartCount(){$('#cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0)}
function renderCart(){$('#cartItems').innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`<div class="admin-row"><div><strong>${esc(p.name)}</strong><div class="muted">${i.qty} × ${money(p.price)}</div></div><div class="admin-actions"><button onclick="changeQty(${p.id},-1)">−</button><button onclick="changeQty(${p.id},1)">+</button></div></div>`:''}).join(''):'<p class="muted">Dein Warenkorb ist leer.</p>';$('#cartTotal').textContent=money(cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0))}
function changeQty(id,d){const i=cart.find(x=>x.id===id),p=products.find(x=>x.id===id);if(!i)return;if(d>0&&p&&i.qty>=p.stock)return toast('Nicht mehr auf Lager');i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart();updateCartCount();renderCart()}
window.addToCart=addToCart;window.editProduct=async id=>{if(!merchant)return;const {data}=await db.from('products').select('*,categories(name)').eq('id',id).eq('merchant_id',merchant.id).single();if(data)openProduct({...data,category:data.categories?.name||''})};window.deleteProduct=async id=>{if(!merchant||!confirm('Produkt wirklich löschen?'))return;const {error}=await db.from('products').delete().eq('id',id).eq('merchant_id',merchant.id);if(error)toast(error.message);else{toast('Produkt gelöscht');await loadProducts();await renderDashboard()}};window.changeQty=changeQty;
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));['search','categoryFilter','sort'].forEach(id=>$('#'+id).addEventListener('input',renderShop));
$('#authBtn').addEventListener('click',async()=>{if(currentUser){await db.auth.signOut();toast('Abgemeldet');switchView('shop');await refreshAuth()}else{$('#authModal').classList.remove('hidden');setAuthMode('login')}});$('#authForm').addEventListener('submit',submitAuth);
$('#addProductBtn').addEventListener('click',async()=>{if(!currentUser){$('#authModal').classList.remove('hidden');setAuthMode('login');return}if(!merchant&&!(await createMerchant()))return;openProduct()});
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();if(!merchant)return;const id=$('#productId').value;const name=$('#name').value.trim(),categoryName=$('#category').value.trim();let {data:cat}=await db.from('categories').select('id').ilike('name',categoryName).maybeSingle();if(!cat){const slug=categoryName.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const res=await db.from('categories').insert({name:categoryName,slug}).select('id').single();if(res.error){toast(res.error.message);return}cat=res.data}const payload={merchant_id:merchant.id,category_id:cat.id,name,slug:(name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now()),price:Number($('#price').value),stock:Number($('#stock').value),image_url:$('#image').value.trim()||null,description:$('#description').value.trim(),active:true,updated_at:new Date().toISOString()};let res;if(id)res=await db.from('products').update(payload).eq('id',Number(id)).eq('merchant_id',merchant.id);else res=await db.from('products').insert(payload);if(res.error){toast(res.error.message);return}$('#productModal').classList.add('hidden');toast('Produkt gespeichert');await loadProducts();await renderDashboard()});
$('#cartBtn').addEventListener('click',()=>{$('#cartModal').classList.remove('hidden');renderCart()});$('#checkoutBtn').addEventListener('click',()=>toast('Checkout kommt im nächsten Ausbau'));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.add('hidden')));db.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0));
updateCartCount();loadProducts();refreshAuth();