const SUPABASE_URL='https://oansbivkczjbtxaknks.supabase.co';
const SUPABASE_KEY='sb_publishable_9tDZPZ9KmCjHZqVXBmO-1g_8Aqpu8qE';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let products=[],cart=JSON.parse(localStorage.getItem('rebel_cart')||'[]'),currentUser=null,merchant=null,authMode='login';
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function loadProducts(){let r=await db.from('products').select('id,name,slug,description,price,stock,image_url,created_at,category_id').eq('active',true).order('created_at',{ascending:false});if(r.error){console.error(r.error);toast('Produkte konnten nicht geladen werden');return}const rows=r.data||[];const ids=[...new Set(rows.map(p=>p.category_id).filter(Boolean))];let catMap={};if(ids.length){const c=await db.from('categories').select('id,name').in('id',ids);if(!c.error)(c.data||[]).forEach(x=>catMap[x.id]=x.name)}products=rows.map(p=>({...p,category:catMap[p.category_id]||'Produkte',image:p.image_url||''}));renderShop()}
function categories(){const s=$('#categoryFilter'),cats=[...new Set(products.map(p=>p.category))].sort();s.innerHTML='<option value="all">Alle Kategorien</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}
function renderShop(){categories();let q=$('#search').value.toLowerCase(),cat=$('#categoryFilter').value,list=products.filter(p=>(p.name+' '+(p.description||'')).toLowerCase().includes(q)&&(cat==='all'||p.category===cat));const sort=$('#sort').value;if(sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(sort==='priceDesc')list.sort((a,b)=>b.price-a.price);$('#productGrid').innerHTML=list.map(p=>`<article class="product">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'<div class="placeholder">RK</div>'}<div class="product-body"><div class="muted">${esc(p.category)}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description||'')}</p><div class="price">${money(p.price)}</div><button class="add" ${p.stock<=0?'disabled':''} onclick="addToCart(${p.id})">${p.stock>0?'In den Warenkorb':'Ausverkauft'}</button></div></article>`).join('')||'<p>Keine Produkte gefunden.</p>'}
async function refreshAuth(){const {data}=await db.auth.getSession();currentUser=data.session?.user||null;if(currentUser){$('#authStatus').textContent=currentUser.email;$('#authBtn').textContent='Abmelden';await loadMerchant()}else{$('#authStatus').textContent='';$('#authBtn').textContent='Anmelden';merchant=null}}
async function loadMerchant(){if(!currentUser)return;const {data,error}=await db.from('merchants').select('*').eq('owner_id',currentUser.id).maybeSingle();if(error)console.error(error);merchant=data||null}
function setAuthMode(mode){authMode=mode;$('#authTitle').textContent=mode==='login'?'Anmelden':'Konto erstellen';$('#authSubmit').textContent=mode==='login'?'Anmelden':'Konto erstellen';$('#authNameWrap').classList.toggle('hidden',mode==='login');$('#authSwitchText').innerHTML=mode==='login'?'Noch kein Konto? <button type="button" id="authSwitch" class="link-btn">Konto erstellen</button>':'Schon ein Konto? <button type="button" id="authSwitch" class="link-btn">Anmelden</button>';$('#authSwitch').onclick=()=>setAuthMode(mode==='login'?'signup':'login')}
async function submitAuth(e){e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();if(authMode==='login'){const {error}=await db.auth.signInWithPassword({email,password});if(error)return toast(error.message);toast('Erfolgreich angemeldet')}else{const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0]}}});if(error)return toast(error.message);toast(data.session?'Konto erstellt':'Bitte E-Mail bestätigen')}$('#authModal').classList.add('hidden');await refreshAuth()}
async function createMerchant(){if(!currentUser)return false;if(merchant)return true;const shopName=prompt('Wie soll dein Händler-Shop heißen?','Mein Rebelkultur Shop');if(!shopName)return false;let slug=shopName.toLowerCase().trim().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'shop';slug+=`-${currentUser.id.slice(0,8)}`;const {data,error}=await db.from('merchants').insert({owner_id:currentUser.id,shop_name:shopName,slug,status:'pending'}).select().single();if(error)return toast(error.message),false;merchant=data;toast('Händler-Shop angelegt');return true}
function setDashTab(tab){document.querySelectorAll('.dash-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.dash-panel').forEach(p=>p.classList.add('hidden'));const map={overview:'#dashboardOverview',products:'#dashboardProducts',orders:'#dashboardOrders',settings:'#dashboardSettings',legal:'#dashboardLegal',checklist:'#dashboardChecklist',faq:'#dashboardFaq',marketing:'#dashboardMarketing'};$(map[tab]||map.overview)?.classList.remove('hidden');if(tab==='products')renderProductsFull();if(tab==='orders')renderOrdersFull();if(tab==='settings')loadSettingsForm()}
function productRows(mine){return mine.map(p=>`<div class="admin-row"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.category)} · ${money(p.price)} · Bestand ${p.stock}</div></div><div class="admin-actions"><button onclick="editProduct(${p.id})">Bearbeiten</button><button onclick="deleteProduct(${p.id})">Löschen</button></div></div>`).join('')||'<p class="muted">Noch keine Produkte. Lege dein erstes Produkt an.</p>'}
async function getMine(){if(!merchant)return[];const {data,error}=await db.from('products').select('id,name,description,price,stock,image_url,created_at,category_id').eq('merchant_id',merchant.id).order('created_at',{ascending:false});if(error){toast(error.message);return[]}const rows=data||[];const ids=[...new Set(rows.map(p=>p.category_id).filter(Boolean))];let catMap={};if(ids.length){const c=await db.from('categories').select('id,name').in('id',ids);if(!c.error)(c.data||[]).forEach(x=>catMap[x.id]=x.name)}return rows.map(p=>({...p,category:catMap[p.category_id]||'Produkte'}))}
async function renderProductsFull(){const mine=await getMine();$('#adminProductsFull').innerHTML=productRows(mine)}
async function renderOrdersFull(){await renderMerchantOrders('#ordersFull')}
async function renderMerchantOrders(target='#orders'){if(!merchant){$(target).innerHTML='<p class="muted">Kein Händler-Shop vorhanden.</p>';return}const {data:prodIds}=await db.from('products').select('id').eq('merchant_id',merchant.id);const ids=(prodIds||[]).map(p=>p.id);if(!ids.length){$(target).innerHTML='<p class="muted">Noch keine Bestellungen für diesen Shop.</p>';return}const {data:items,error}=await db.from('order_items').select('order_id,product_id,product_name,quantity,unit_price,orders(id,status,total,created_at)').in('product_id',ids);if(error){$(target).innerHTML='<p class="muted">Bestellungen konnten nicht geladen werden.</p>';return}const grouped={};(items||[]).forEach(i=>{const o=i.orders;if(!o)return;(grouped[o.id]??={...o,items:[]}).items.push(i)});const orders=Object.values(grouped);$(target).innerHTML=orders.map(o=>`<div class="order-row"><div><strong>Bestellung #${o.id}</strong><div class="muted">${new Date(o.created_at).toLocaleString('de-DE')} · ${o.items.map(i=>`${esc(i.product_name)} × ${i.quantity}`).join(', ')}</div></div><div><strong>${money(o.total)}</strong><select onchange="changeOrderStatus(${o.id},this.value)"><option ${o.status==='new'?'selected':''} value="new">Offen</option><option ${o.status==='paid'?'selected':''} value="paid">Bezahlt</option><option ${o.status==='processing'?'selected':''} value="processing">In Bearbeitung</option><option ${o.status==='shipped'?'selected':''} value="shipped">Versendet</option><option ${o.status==='completed'?'selected':''} value="completed">Abgeschlossen</option><option ${o.status==='cancelled'?'selected':''} value="cancelled">Storniert</option></select></div></div>`).join('')||'<p class="muted">Noch keine Bestellungen für diesen Shop.</p>'}
window.changeOrderStatus=async(id,status)=>{const {error}=await db.rpc('merchant_set_order_status',{p_order_id:id,p_status:status});if(error)toast(error.message);else{toast('Bestellstatus aktualisiert');await renderMerchantOrders();await renderOrdersFull()}};
async function renderDashboard(){if(!currentUser){$('#stats').innerHTML='<div class="stat"><strong>🔒</strong><span>Anmeldung erforderlich</span></div>';$('#adminProducts').innerHTML='<p class="muted">Bitte anmelden, um den Händlerbereich zu öffnen.</p>';$('#orders').innerHTML='<p class="muted">Noch nicht angemeldet.</p>';return}if(!merchant&&!(await createMerchant()))return;const mine=await getMine();$('#stats').innerHTML=`<div class="stat"><strong>${mine.length}</strong><span>Produkte</span></div><div class="stat"><strong>${mine.reduce((s,p)=>s+p.stock,0)}</strong><span>Artikel auf Lager</span></div><div class="stat"><strong>${money(mine.reduce((s,p)=>s+Number(p.price)*p.stock,0))}</strong><span>Lagerwert</span></div><div class="stat"><strong>${esc(merchant.status)}</strong><span>Shop-Status</span></div>`;$('#productTotal').textContent=`${mine.length} Produkte`;$(`#adminProducts`).innerHTML=productRows(mine);await renderMerchantOrders()}
function switchView(view){$('#shopView').classList.toggle('hidden',view!=='shop');$('#dashboardView').classList.toggle('hidden',view!=='dashboard');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='dashboard'){setDashTab('overview');renderDashboard()}else renderShop()}
function openProduct(p){if(!merchant)return toast('Bitte zuerst einen Händler-Shop anlegen');$('#productModal').classList.remove('hidden');$('#modalTitle').textContent=p?'Produkt bearbeiten':'Produkt hinzufügen';$('#productId').value=p?.id||'';$('#name').value=p?.name||'';$('#category').value=p?.category||'';$('#price').value=p?.price??'';$('#stock').value=p?.stock??'';$('#image').value=p?.image_url||p?.image||'';$('#description').value=p?.description||''}
window.addToCart=async id=>{const p=products.find(x=>x.id===id);if(!p||p.stock<1)return;const i=cart.find(x=>x.id===id);if(i){if(i.qty>=p.stock)return toast('Nicht mehr auf Lager');i.qty++}else cart.push({id,qty:1});saveCart();updateCartCount();toast('Produkt hinzugefügt')};
function saveCart(){localStorage.setItem('rebel_cart',JSON.stringify(cart))}function updateCartCount(){$('#cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0)}
function renderCart(){$('#cartItems').innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`<div class="admin-row"><div><strong>${esc(p.name)}</strong><div class="muted">${i.qty} × ${money(p.price)}</div></div><div class="admin-actions"><button onclick="changeQty(${p.id},-1)">−</button><button onclick="changeQty(${p.id},1)">+</button></div></div>`:''}).join(''):'<p class="muted">Dein Warenkorb ist leer.</p>';$('#cartTotal').textContent=money(cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0))}
window.changeQty=(id,d)=>{const i=cart.find(x=>x.id===id),p=products.find(x=>x.id===id);if(!i)return;if(d>0&&p&&i.qty>=p.stock)return toast('Nicht mehr auf Lager');i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart();updateCartCount();renderCart()};
async function checkout(){if(!currentUser){toast('Bitte anmelden, bevor du bestellst');$('#cartModal').classList.add('hidden');$('#authModal').classList.remove('hidden');setAuthMode('login');return}if(!cart.length)return toast('Warenkorb ist leer');$('#cartModal').classList.add('hidden');$('#checkoutName').value=currentUser.user_metadata?.display_name||'';$('#checkoutEmail').value=currentUser.email||'';$('#checkoutAddress').value='';$('#checkoutModal').classList.remove('hidden')}
async function submitCheckout(e){e.preventDefault();if(!currentUser||!cart.length)return;const items=cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?{product_id:p.id,product_name:p.name,quantity:i.qty,unit_price:Number(p.price)}:null}).filter(Boolean);const total=items.reduce((s,i)=>s+i.quantity*i.unit_price,0);const {data:order,error}=await db.from('orders').insert({customer_id:currentUser.id,status:'new',total}).select('id').single();if(error)return toast(error.message);const {error:itemError}=await db.from('order_items').insert(items.map(i=>({...i,order_id:order.id})));if(itemError){await db.from('orders').delete().eq('id',order.id);return toast(itemError.message)}cart=[];saveCart();updateCartCount();$('#checkoutModal').classList.add('hidden');$('#successText').textContent=`Bestellung #${order.id} wurde gespeichert. Wir haben ${$('#checkoutEmail').value} als Kontaktadresse übernommen.`;$('#successModal').classList.remove('hidden');await loadProducts()}
window.editProduct=async id=>{if(!merchant)return;const {data,error}=await db.from('products').select('*').eq('id',id).eq('merchant_id',merchant.id).single();if(error){toast(error.message);return}let cat='';if(data?.category_id){const c=await db.from('categories').select('name').eq('id',data.category_id).maybeSingle();cat=c.data?.name||''}if(data)openProduct({...data,category:cat})};window.deleteProduct=async id=>{if(!merchant||!confirm('Produkt wirklich löschen?'))return;const {error}=await db.from('products').delete().eq('id',id).eq('merchant_id',merchant.id);if(error)toast(error.message);else{toast('Produkt gelöscht');await loadProducts();await renderDashboard()}};
function loadSettingsForm(){if(!merchant)return;const saved=JSON.parse(localStorage.getItem(`rebel_settings_${merchant.id}`)||'{}');$('#settingShopName').value=saved.shopName||merchant.shop_name||'';$('#settingShopUrl').value=saved.shopUrl||'';$('#settingPayment').value=saved.payment||'';$('#settingOrderEmail').value=saved.orderEmail||currentUser?.email||''}
function saveSettings(){if(!merchant)return;const data={shopName:$('#settingShopName').value.trim(),shopUrl:$('#settingShopUrl').value.trim(),payment:$('#settingPayment').value,orderEmail:$('#settingOrderEmail').value.trim()};localStorage.setItem(`rebel_settings_${merchant.id}`,JSON.stringify(data));toast('Shop-Einstellungen gespeichert')}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.querySelectorAll('.dash-tab').forEach(b=>b.addEventListener('click',()=>setDashTab(b.dataset.tab)));['search','categoryFilter','sort'].forEach(id=>$('#'+id).addEventListener('input',renderShop));
$('#authBtn').addEventListener('click',async()=>{if(currentUser){await db.auth.signOut();toast('Abgemeldet');switchView('shop');await refreshAuth()}else{$('#authModal').classList.remove('hidden');setAuthMode('login')}});$('#authForm').addEventListener('submit',submitAuth);
$('#addProductBtn').addEventListener('click',async()=>{if(!currentUser){$('#authModal').classList.remove('hidden');setAuthMode('login');return}if(!merchant&&!(await createMerchant()))return;openProduct()});
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();if(!merchant)return;const id=$('#productId').value,name=$('#name').value.trim(),categoryName=$('#category').value.trim();const c=await db.rpc('ensure_category',{p_name:categoryName});if(c.error)return toast(c.error.message);const cat=c.data;const base={merchant_id:merchant.id,category_id:cat,name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now(),price:Number($('#price').value),stock:Number($('#stock').value),image_url:$('#image').value.trim()||null,description:$('#description').value.trim(),active:true,updated_at:new Date().toISOString()};const r=id?await db.from('products').update(base).eq('id',Number(id)).eq('merchant_id',merchant.id):await db.from('products').insert(base);if(r.error)return toast(r.error.message);$('#productModal').classList.add('hidden');toast('Produkt gespeichert');await loadProducts();await renderDashboard()});
$('#cartBtn').addEventListener('click',()=>{$('#cartModal').classList.remove('hidden');renderCart()});$('#checkoutBtn').addEventListener('click',checkout);$('#checkoutForm').addEventListener('submit',submitCheckout);$('#saveSettings').addEventListener('click',saveSettings);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.add('hidden')));db.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0));updateCartCount();loadProducts();refreshAuth();