(()=>{
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
  function init(){
    const shop=document.querySelector('#shopView'),hero=shop?.querySelector('.hero'),toolbar=shop?.querySelector('.toolbar');
    if(!shop||!hero||!toolbar||document.querySelector('#rkMarketplaceHome'))return false;
    const home=document.createElement('section');home.id='rkMarketplaceHome';
    home.innerHTML=`<div class="rk-market-hero"><div class="rk-market-copy"><span class="rk-kicker">REBELKULTUR MARKTPLATZ</span><h1>Entdecke. Vergleiche. <span>Finde deinen Shop.</span></h1><p>Produkte von unabhängigen Händlern – an einem Ort. Suche, entdecke Neuheiten und finde passende Produkte automatisch.</p><div class="rk-market-actions"><button class="primary" type="button" data-focus-search>Produkte entdecken</button><button class="secondary" type="button" data-show-merchants>Händler entdecken</button></div></div><div class="rk-market-panel"><strong>Was suchst du?</strong><div class="rk-quick-search"><input id="rkHomeSearch" type="search" placeholder="z. B. Kleidung, Zubehör, Geschenke …" autocomplete="off"><button type="button" data-run-search>⌕</button></div><div id="rkCategoryChips" class="rk-category-chips"></div></div></div><div class="rk-market-sections"><div class="rk-section-head"><div><span class="rk-kicker">MARKTPLATZ</span><h2>Stöbere nach Interesse</h2></div><span class="rk-section-note">Händlerübergreifend</span></div><div class="rk-market-cards"><button data-mode="popular"><b>🔥 Beliebt</b><span>Was andere gerade entdecken</span></button><button data-mode="new"><b>✨ Neu</b><span>Frisch eingestellte Produkte</span></button><button data-mode="personal"><b>♥ Für dich</b><span>Passend zu deinen Interessen</span></button><button data-mode="all"><b>▦ Alle Produkte</b><span>Den gesamten Marktplatz durchsuchen</span></button></div></div>`;
    hero.replaceWith(home);
    const cats=()=>{const ps=window.products||[],names=[...new Set(ps.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de')).slice(0,12);const el=document.querySelector('#rkCategoryChips');if(!el)return;el.innerHTML=names.map(c=>`<button type="button" data-cat="${esc(c)}">${esc(c)}</button>`).join('')||'<span class="muted">Kategorien werden geladen …</span>';el.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{const f=document.querySelector('#categoryFilter');if(f){f.value=b.dataset.cat;f.dispatchEvent(new Event('change',{bubbles:true}))}document.querySelector('#products')?.scrollIntoView({behavior:'smooth',block:'start'})})};
    const search=q=>{const input=document.querySelector('#search');if(!input)return;input.value=q;input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#products')?.scrollIntoView({behavior:'smooth',block:'start'})};
    document.querySelector('[data-focus-search]')?.addEventListener('click',()=>{document.querySelector('#rkHomeSearch')?.focus()});
    document.querySelector('[data-run-search]')?.addEventListener('click',()=>search(document.querySelector('#rkHomeSearch')?.value||''));
    document.querySelector('#rkHomeSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')search(e.currentTarget.value)});
    document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{const tab=document.querySelector(`.rk-tab[data-mode="${b.dataset.mode}"]`);if(tab){tab.click();document.querySelector('#rkDiscovery')?.scrollIntoView({behavior:'smooth',block:'start'})}else if(b.dataset.mode==='all')document.querySelector('#products')?.scrollIntoView({behavior:'smooth',block:'start'})}));
    document.querySelector('[data-show-merchants]')?.addEventListener('click',()=>{const dir=document.querySelector('#merchantDirectory');(dir||document.querySelector('#productGrid'))?.scrollIntoView({behavior:'smooth',block:'start'})});
    let tries=0;const tick=()=>{cats();if((window.products||[]).length||tries>20)return;tries++;setTimeout(tick,300)};tick();return true;
  }
  const style=document.createElement('style');style.textContent=`#rkMarketplaceHome{margin:0 auto 24px;max-width:1180px}.rk-market-hero{display:grid;grid-template-columns:1.35fr .8fr;gap:24px;align-items:stretch;padding:42px 34px;border-radius:24px;background:linear-gradient(135deg,#17131c,#30203e);color:#fff;box-shadow:0 16px 50px #17101f22}.rk-market-copy{display:flex;flex-direction:column;justify-content:center}.rk-kicker{font-size:11px;font-weight:900;letter-spacing:.15em;opacity:.8}.rk-market-copy h1{font-size:clamp(32px,5vw,58px);line-height:1.02;margin:10px 0 14px;max-width:720px}.rk-market-copy h1 span{display:block}.rk-market-copy p{font-size:17px;line-height:1.55;max-width:690px;color:#e9e3ef;margin:0}.rk-market-actions{display:flex;gap:10px;margin-top:24px;flex-wrap:wrap}.rk-market-actions .secondary{background:#fff;color:#17131c}.rk-market-panel{align-self:center;background:#fff;color:#17131c;border-radius:20px;padding:22px;box-shadow:0 14px 36px #0004}.rk-market-panel strong{font-size:18px}.rk-quick-search{display:flex;margin-top:12px}.rk-quick-search input{min-width:0;flex:1;border:1px solid #dcd5e3;border-right:0;border-radius:12px 0 0 12px;padding:13px;font-size:15px}.rk-quick-search button{width:50px;border:0;border-radius:0 12px 12px 0;background:#17131c;color:#fff;font-size:21px;cursor:pointer}.rk-category-chips{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.rk-category-chips button{border:1px solid #ded7e5;background:#faf8fc;border-radius:999px;padding:7px 10px;cursor:pointer}.rk-category-chips button:hover{background:#eee8f4}.rk-market-sections{padding:26px 4px 0}.rk-section-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:12px}.rk-section-head h2{margin:5px 0 0;font-size:25px}.rk-section-note{font-size:12px;color:#777080}.rk-market-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.rk-market-cards button{text-align:left;border:1px solid #e4ddea;background:#fff;border-radius:16px;padding:17px;cursor:pointer;transition:.15s}.rk-market-cards button:hover{transform:translateY(-2px);box-shadow:0 8px 24px #2b173d12}.rk-market-cards b,.rk-market-cards span{display:block}.rk-market-cards b{font-size:16px}.rk-market-cards span{margin-top:5px;color:#756d7b;font-size:12px;line-height:1.4}@media(max-width:800px){.rk-market-hero{grid-template-columns:1fr;padding:28px 22px}.rk-market-cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){#rkMarketplaceHome{margin-left:12px;margin-right:12px}.rk-market-cards{grid-template-columns:1fr}.rk-market-copy h1{font-size:34px}}`;document.head.appendChild(style);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,900));else setTimeout(init,900);
})();
