(()=>{
const db=window.supabase.createClient(window.__RK_SUPABASE_URL,window.__RK_SUPABASE_KEY);
async function merchant(){const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data}=await db.from('merchants').select('id,shop_name,slug').eq('owner_id',user.id).maybeSingle();return data||null}
async function render(){const panel=document.querySelector('#dashboardDesign');if(!panel||panel.classList.contains('hidden')||panel.querySelector('#merchantSeoPanel'))return;const m=await merchant();if(!m)return;const a=document.createElement('article');a.className='panel';a.id='merchantSeoPanel';a.innerHTML='<div class="panel-head"><h3>SEO & Google</h3><span>Öffentlicher Shop</span></div><p class="muted">Titel und Beschreibung für Suchmaschinen und Social-Media-Vorschauen.</p><div class="settings-grid"><label>SEO-Titel <small>(max. 70 Zeichen)</small><input id="seoTitle" maxlength="70" placeholder="'+(m.shop_name||'Mein Shop')+' – Produkte & Angebote"></label><label>Meta-Beschreibung <small>(max. 160 Zeichen)</small><textarea id="seoDescription" maxlength="160" rows="3" placeholder="Kurze Beschreibung deines Shops für Google"></textarea><span id="seoDescCount" class="muted">0 / 160</span></label><label>Keywords <small>(optional)</small><input id="seoKeywords" maxlength="500" placeholder="z. B. Zubehör, Kleidung, Produkte"></label><label>Vorschaubild URL <small>(optional)</small><input id="seoImage" type="url" maxlength="1000" placeholder="https://…"></label></div><div id="seoPreview" style="margin-top:14px;padding:16px;border:1px solid #e0d8e8;border-radius:15px"><strong>Google-Vorschau</strong><div id="seoPreviewTitle" style="margin-top:8px;font-size:18px"></div><div id="seoPreviewUrl" class="muted"></div><p id="seoPreviewDesc" style="margin-bottom:0"></p></div><div style="margin-top:14px"><button id="saveMerchantSeo" class="primary">SEO-Einstellungen speichern</button> <span id="seoSaveHint" class="muted"></span></div>';panel.appendChild(a);['seoTitle','seoDescription','seoKeywords','seoImage'].forEach(id=>a.querySelector('#'+id).addEventListener('input',preview));a.querySelector('#saveMerchantSeo').onclick=save;await load()}
async function load(){const m=await merchant();if(!m)return;const {data,error}=await db.rpc('merchant_get_seo',{p_merchant_id:m.id});if(error){console.error(error);return}const d=data||{};document.querySelector('#seoTitle').value=d.seo_title||'';document.querySelector('#seoDescription').value=d.seo_description||'';document.querySelector('#seoKeywords').value=d.seo_keywords||'';document.querySelector('#seoImage').value=d.og_image_url||'';preview()}
function preview(){const t=document.querySelector('#seoTitle'),d=document.querySelector('#seoDescription');if(!t)return;const title=t.value||'Dein Shop',desc=d.value||'Beschreibung deines Shops';document.querySelector('#seoDescCount').textContent=desc.length+' / 160';document.querySelector('#seoPreviewTitle').textContent=title;document.querySelector('#seoPreviewDesc').textContent=desc;merchant().then(m=>{if(m)document.querySelector('#seoPreviewUrl').textContent=location.origin+location.pathname+'?shop='+m.slug})}
async function save(){const m=await merchant();if(!m)return;const b=document.querySelector('#seoSaveHint'),btn=document.querySelector('#saveMerchantSeo');btn.disabled=true;b.textContent='Speichert …';const {error}=await db.rpc('merchant_save_seo',{p_merchant_id:m.id,p_seo_title:document.querySelector('#seoTitle').value,p_seo_description:document.querySelector('#seoDescription').value,p_seo_keywords:document.querySelector('#seoKeywords').value,p_og_image_url:document.querySelector('#seoImage').value});btn.disabled=false;b.textContent=error?'Fehler beim Speichern':'✓ SEO-Einstellungen gespeichert';if(error)console.error(error);else setTimeout(()=>b.textContent='',2500)}
new MutationObserver(render).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
