(function(){
  const supabaseClient=window.supabase&&window.supabase.createClient;
  const dbRef=window.db||window.rebelDb;
  function ready(){return window.currentUser&&window.db}
  function esc2(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function addNavButton(){const nav=document.querySelector('header nav');if(!nav||document.getElementById('merchantOnboardNav'))return;const b=document.createElement('button');b.id='merchantOnboardNav';b.className='nav-btn merchant-onboard-nav';b.textContent='Händler werden';b.addEventListener('click',()=>openOnboard());nav.appendChild(b)}
  function addModal(){if(document.getElementById('merchantOnboardModal'))return;const wrap=document.createElement('div');wrap.id='merchantOnboardModal';wrap.className='modal hidden';wrap.innerHTML=`<div class="modal-card merchant-onboard"><button class="close" data-onboard-close>×</button><div class="merchant-onboard-head"><div class="merchant-onboard-badge">RK</div><div><h2>Händler werden</h2><div class="muted">Richte deinen eigenen Shop auf Rebelkultur Shops ein.</div></div></div><form id="merchantOnboardForm"><div class="merchant-onboard-grid"><label>Shop-Name<input id="onboardShopName" required maxlength="80" placeholder="z. B. Muster-Shop"></label><label>Kontakt-E-Mail<input id="onboardEmail" type="email" required autocomplete="email" placeholder="shop@example.de"></label><label class="full">Shop-Beschreibung<textarea id="onboardDescription" rows="4" maxlength="500" placeholder="Was bietest du an?"></textarea></label><label>Shop-URL<input id="onboardUrl" type="url" placeholder="https://…"></label><label>Logo-URL<input id="onboardLogo" type="url" placeholder="https://…"></label></div><p class="merchant-onboard-note">Nach dem Absenden wird dein Händlerkonto zunächst als <strong>„ausstehend“</strong> geführt. Nach der Freigabe kannst du deinen Shop veröffentlichen und Produkte verkaufen.</p><div class="merchant-onboard-actions"><button type="button" class="secondary" data-onboard-close>Abbrechen</button><button type="submit" class="primary">Händlerkonto einreichen</button></div></form></div>`;document.body.appendChild(wrap);wrap.querySelectorAll('[data-onboard-close]').forEach(b=>b.addEventListener('click',()=>wrap.classList.add('hidden')));wrap.querySelector('#merchantOnboardForm').addEventListener('submit',submitOnboard)}
  async function openOnboard(){addModal();const modal=document.getElementById('merchantOnboardModal');if(!window.currentUser){document.getElementById('authModal')?.classList.remove('hidden');if(typeof setAuthMode==='function')setAuthMode('login');return}if(window.merchant){loadMerchantForm(window.merchant)}else{document.getElementById('onboardShopName').value='';document.getElementById('onboardEmail').value=window.currentUser.email||'';document.getElementById('onboardDescription').value='';document.getElementById('onboardUrl').value='';document.getElementById('onboardLogo').value=''}modal.classList.remove('hidden')}
  function loadMerchantForm(m){document.getElementById('onboardShopName').value=m.shop_name||'';document.getElementById('onboardEmail').value=m.contact_email||window.currentUser?.email||'';document.getElementById('onboardDescription').value=m.description||'';document.getElementById('onboardUrl').value=m.shop_url||'';document.getElementById('onboardLogo').value=m.logo_url||''}
  async function submitOnboard(e){e.preventDefault();if(!window.currentUser||!window.db)return;const name=document.getElementById('onboardShopName').value.trim();const email=document.getElementById('onboardEmail').value.trim();const desc=document.getElementById('onboardDescription').value.trim();const url=document.getElementById('onboardUrl').value.trim()||null;const logo=document.getElementById('onboardLogo').value.trim()||null;if(!name)return;let slug=name.toLowerCase().replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'shop';slug+='-'+window.currentUser.id.slice(0,8);const payload={shop_name:name,description:desc,shop_url:url,logo_url:logo,contact_email:email};let result;if(window.merchant){result=await window.db.from('merchants').update(payload).eq('id',window.merchant.id).eq('owner_id',window.currentUser.id).select().single()}else{result=await window.db.from('merchants').insert({...payload,owner_id:window.currentUser.id,slug,status:'pending'}).select().single()}if(result.error){if(typeof toast==='function')toast(result.error.message);return}window.merchant=result.data;document.getElementById('merchantOnboardModal').classList.add('hidden');if(typeof toast==='function')toast('Händlerkonto gespeichert');if(typeof renderDashboard==='function')renderDashboard()}
  window.openMerchantOnboarding=openOnboard;addNavButton();addModal();})();