(function(){
  const URL='https://oansbivjkczjbtxaknks.supabase.co';
  const KEY='sb_publishable_9tDZPZ9KmCjHZqVXBmO-1g_8Aqpu8qE';
  const db=window.supabase.createClient(URL,KEY);
  const FN=(name)=>`${URL}/functions/v1/${name}`;
  const $=s=>document.querySelector(s);
  const toast=t=>window.toast?window.toast(t):alert(t);
  async function session(){return (await db.auth.getSession()).data.session||null}
  async function call(name,body){const s=await session();if(!s)throw new Error('Bitte zuerst anmelden.');const r=await fetch(FN(name),{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(body||{})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Serverfehler');return data}
  function injectStripeCard(){const panel=$('#dashboardSettings');if(!panel||$('#stripeConnectCard'))return;const card=document.createElement('article');card.id='stripeConnectCard';card.className='panel';card.style.marginTop='18px';card.innerHTML=`<h3>Stripe-Zahlungen</h3><p id="stripeConnectStatus" class="muted">Verbinde deinen Händler-Shop mit Stripe, damit Kunden online bezahlen können.</p><button id="stripeConnectBtn" class="primary" type="button">Stripe verbinden</button><p class="muted" style="margin-top:10px">Die Stripe-Schlüssel müssen unter Supabase → Edge Functions → Secrets hinterlegt sein. Nicht in den Browser-Code oder GitHub eintragen.</p>`;panel.appendChild(card);$('#stripeConnectBtn').addEventListener('click',async()=>{try{$('#stripeConnectBtn').disabled=true;$('#stripeConnectStatus').textContent='Stripe-Verbindung wird vorbereitet …';const data=await call('stripe-connect-onboard',{});if(data.connected){$('#stripeConnectStatus').textContent='Stripe ist bereits verbunden.';$('#stripeConnectBtn').textContent='Stripe verbunden';}else if(data.onboarding_url){window.location.href=data.onboarding_url}else throw new Error('Keine Stripe-Onboarding-URL erhalten.')}catch(e){$('#stripeConnectStatus').textContent=e.message;toast(e.message)}finally{$('#stripeConnectBtn').disabled=false}})}
  function patchCheckout(){const btn=$('#checkoutBtn'),form=$('#checkoutForm');if(!btn||!form||btn.dataset.stripePatched)return;const newBtn=btn.cloneNode(true);btn.replaceWith(newBtn);const newForm=form.cloneNode(true);form.replaceWith(newForm);newBtn.dataset.stripePatched='1';newBtn.addEventListener('click',async()=>{try{const s=await session();if(!s){toast('Bitte anmelden, bevor du bezahlst.');$('#authModal')?.classList.remove('hidden');return}const raw=JSON.parse(localStorage.getItem('rebel_cart')||'[]');if(!raw.length)return toast('Warenkorb ist leer.');const ids=raw.map(x=>Number(x.id));const {data,error}=await db.from('products').select('id,merchant_id').in('id',ids).eq('active',true);if(error)throw error;if(!data?.length)return toast('Ein Produkt ist nicht mehr verfügbar.');if([...new Set(data.map(p=>p.merchant_id))].length!==1)return toast('Bitte pro Bestellung nur Produkte eines Händlers kaufen.');$('#cartModal')?.classList.add('hidden');$('#checkoutName').value=s.user.user_metadata?.display_name||s.user.email?.split('@')[0]||'';$('#checkoutEmail').value=s.user.email||'';$('#checkoutAddress').value='';newForm.dataset.items=JSON.stringify(raw);$('#checkoutModal')?.classList.remove('hidden')}catch(e){toast(e.message)}});newForm.addEventListener('submit',async e=>{e.preventDefault();const btn2=newForm.querySelector('button[type="submit"]');try{const raw=JSON.parse(newForm.dataset.items||localStorage.getItem('rebel_cart')||'[]');const data=await call('stripe-create-checkout-v2',{cart:raw,name:$('#checkoutName').value.trim(),email:$('#checkoutEmail').value.trim(),address:$('#checkoutAddress').value.trim()});if(!data.checkout_url)throw new Error('Stripe Checkout konnte nicht gestartet werden.');if(btn2){btn2.disabled=true;btn2.textContent='Weiter zu Stripe …'}window.location.href=data.checkout_url}catch(e){toast(e.message);if(btn2){btn2.disabled=false;btn2.textContent='Mit Stripe bezahlen'}}})}
  async function paymentReturn(){const qs=new URLSearchParams(location.search);const payment=qs.get('payment'),sid=qs.get('session_id');if(payment==='cancelled'){toast('Die Zahlung wurde abgebrochen.');return}if(payment!=='success'||!sid)return;try{const data=await call('stripe-session-status',{session_id:sid});if(data.paid){localStorage.removeItem('rebel_cart');window.history.replaceState({},'',window.location.pathname);const text=$('#successText');if(text)text.textContent=`Zahlung erfolgreich. Bestellung #${data.order_id} wurde bezahlt.`;$('#successModal')?.classList.remove('hidden')}}catch(e){toast(e.message)}}
  function watch(){injectStripeCard();patchCheckout();paymentReturn();setTimeout(()=>{injectStripeCard();patchCheckout()},900)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();
