-- Rebelkultur Shops – initial relational data model
-- PostgreSQL / Supabase compatible.

create table if not exists profiles (
  id uuid primary key,
  role text not null default 'customer' check (role in ('customer','merchant','admin')),
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists merchants (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references profiles(id) on delete cascade,
  shop_name text not null,
  slug text not null unique,
  status text not null default 'pending' check (status in ('pending','approved','suspended')),
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  merchant_id uuid not null references merchants(id) on delete cascade,
  category_id bigint references categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  price numeric(10,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  name text not null,
  sku text unique,
  price numeric(10,2) check (price >= 0),
  stock integer not null default 0 check (stock >= 0)
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references profiles(id) on delete set null,
  status text not null default 'new' check (status in ('new','paid','processing','shipped','completed','cancelled')),
  total numeric(10,2) not null default 0 check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  variant_id bigint references product_variants(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0)
);

create index if not exists products_merchant_idx on products(merchant_id);
create index if not exists products_category_idx on products(category_id);
create index if not exists orders_customer_idx on orders(customer_id);
create index if not exists order_items_order_idx on order_items(order_id);

insert into categories (name, slug) values
 ('Hoodies','hoodies'),
 ('T-Shirts','t-shirts'),
 ('Polos','polos'),
 ('Accessories','accessories')
on conflict (slug) do nothing;
