-- Track checkout stock reservations so unpaid/expired Stripe sessions do not lock inventory.
-- Existing atomic stock functions remain available for compatibility.

create table if not exists public.stock_reservations (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  status text not null default 'reserved' check (status in ('reserved','released','consumed')),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  created_at timestamptz not null default now(),
  released_at timestamptz,
  consumed_at timestamptz
);

create index if not exists stock_reservations_order_idx on public.stock_reservations(order_id);
create index if not exists stock_reservations_expiry_idx on public.stock_reservations(status, expires_at);
create unique index if not exists stock_reservations_reserved_product_uq
  on public.stock_reservations(order_id, product_id) where status = 'reserved';

alter table public.stock_reservations enable row level security;
revoke all on table public.stock_reservations from public, anon, authenticated;
grant all on table public.stock_reservations to service_role;

do $$
begin
  if not exists (select 1 from pg_proc where proname = 'reserve_order_stock') then
    create function public.reserve_order_stock(p_order_id bigint, p_items jsonb)
    returns void language plpgsql security definer set search_path = public as $fn$
    declare item jsonb; v_product_id bigint; v_quantity integer;
    begin
      if p_order_id is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then
        raise exception 'Ungültige Reservierung';
      end if;
      for item in select value from jsonb_array_elements(p_items) loop
        v_product_id := (item->>'product_id')::bigint;
        v_quantity := (item->>'quantity')::integer;
        if v_product_id is null or v_quantity is null or v_quantity < 1 then raise exception 'Ungültige Reservierung'; end if;
        update public.products set stock = stock - v_quantity
          where id=v_product_id and active=true and stock >= v_quantity;
        if not found then raise exception 'Produkt %: nicht genug Bestand oder nicht verfügbar.', v_product_id; end if;
        insert into public.stock_reservations(order_id,product_id,quantity) values(p_order_id,v_product_id,v_quantity);
      end loop;
    exception when others then
      -- Restore every reservation already inserted for this order before propagating the error.
      update public.products p set stock = p.stock + r.quantity
        from public.stock_reservations r
        where r.order_id=p_order_id and r.status='reserved' and r.product_id=p.id;
      delete from public.stock_reservations where order_id=p_order_id and status='reserved';
      raise;
    end;
    $fn$;
  end if;
end $$;

create or replace function public.release_order_stock(p_order_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.products p set stock = p.stock + r.quantity
    from public.stock_reservations r
    where r.order_id=p_order_id and r.status='reserved' and r.product_id=p.id;
  update public.stock_reservations set status='released', released_at=now()
    where order_id=p_order_id and status='reserved';
end;
$$;

create or replace function public.consume_order_stock(p_order_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.stock_reservations set status='consumed', consumed_at=now()
    where order_id=p_order_id and status='reserved';
end;
$$;

create or replace function public.release_expired_stock_reservations()
returns integer language plpgsql security definer set search_path = public as $$
declare v_count integer;
begin
  with expired as (
    select distinct order_id from public.stock_reservations where status='reserved' and expires_at <= now()
  ), released as (
    select public.release_order_stock(order_id) from expired
  ) select count(*) into v_count from expired;
  return coalesce(v_count,0);
end;
$$;

revoke all on function public.reserve_order_stock(bigint,jsonb) from public, anon, authenticated;
revoke all on function public.release_order_stock(bigint) from public, anon, authenticated;
revoke all on function public.consume_order_stock(bigint) from public, anon, authenticated;
revoke all on function public.release_expired_stock_reservations() from public, anon, authenticated;
grant execute on function public.reserve_order_stock(bigint,jsonb) to service_role;
grant execute on function public.release_order_stock(bigint) to service_role;
grant execute on function public.consume_order_stock(bigint) to service_role;
grant execute on function public.release_expired_stock_reservations() to service_role;
