-- Customer-facing order notifications with strict per-customer RLS.
create table if not exists public.order_notifications (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  title text not null,
  message text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists order_notifications_customer_idx
  on public.order_notifications(customer_id, created_at desc);
create index if not exists order_notifications_order_idx
  on public.order_notifications(order_id, created_at desc);

alter table public.order_notifications enable row level security;
revoke all on table public.order_notifications from public, anon;
grant select, update on table public.order_notifications to authenticated;
grant all on table public.order_notifications to service_role;

drop policy if exists "customers read own order notifications" on public.order_notifications;
create policy "customers read own order notifications"
  on public.order_notifications for select
  to authenticated
  using (customer_id = auth.uid());

drop policy if exists "customers mark own notifications read" on public.order_notifications;
create policy "customers mark own notifications read"
  on public.order_notifications for update
  to authenticated
  using (customer_id = auth.uid())
  with check (customer_id = auth.uid());

-- Only expose the fields customers need to change; RLS still limits the row owner.
revoke update on table public.order_notifications from authenticated;
grant update(read_at) on table public.order_notifications to authenticated;

create or replace function public.notify_customer_order_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text;
  v_message text;
begin
  if new.customer_id is null then
    return new;
  end if;

  if new.status is distinct from old.status then
    case new.status
      when 'paid' then
        v_title := 'Zahlung erhalten';
        v_message := format('Deine Bestellung #%s wurde bezahlt.', new.id);
      when 'processing' then
        v_title := 'Bestellung wird bearbeitet';
        v_message := format('Deine Bestellung #%s wird jetzt bearbeitet.', new.id);
      when 'shipped' then
        v_title := 'Bestellung versendet';
        v_message := format('Deine Bestellung #%s wurde versendet.', new.id);
      when 'completed' then
        v_title := 'Bestellung abgeschlossen';
        v_message := format('Deine Bestellung #%s ist abgeschlossen.', new.id);
      when 'cancelled' then
        v_title := 'Bestellung storniert';
        v_message := format('Deine Bestellung #%s wurde storniert.', new.id);
      else
        v_title := null;
    end case;

    if v_title is not null then
      insert into public.order_notifications(customer_id, order_id, title, message)
      values(new.customer_id, new.id, v_title, v_message);
    end if;
  end if;

  if new.tracking_number is distinct from old.tracking_number
     or new.shipping_carrier is distinct from old.shipping_carrier
     or new.tracking_url is distinct from old.tracking_url then
    insert into public.order_notifications(customer_id, order_id, title, message)
    values(
      new.customer_id,
      new.id,
      'Versanddaten aktualisiert',
      format('Die Versanddaten für Bestellung #%s wurden aktualisiert.', new.id)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists orders_customer_notification_trigger on public.orders;
create trigger orders_customer_notification_trigger
after update of status, tracking_number, shipping_carrier, tracking_url on public.orders
for each row execute function public.notify_customer_order_update();

revoke all on function public.notify_customer_order_update() from public, anon, authenticated;
grant execute on function public.notify_customer_order_update() to service_role;
